cosinnus_todo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from cosinnus.utils.url_patterns import api_patterns
from cosinnus_todo import views

app_name = 'todo'

cosinnus_group_patterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^list/$', views.todo_list_create_view, name='list'),
    url(r'^list/move_element/$', views.move_element_view, name='move-element'),
    url(r'^list/(?P<listslug>[^/]+)/$', views.todo_list_create_view, name='list-list'),
    url(r'^list/(?P<listslug>[^/]+)/show/(?P<todoslug>[^/]+)/$', views.todo_list_create_view, name='todo-in-list-list'),
    url(r'^delete/list/(?P<slug>[^/]+)/$', views.todolist_delete_view, name='todolist-delete'),
    
    url(r'^list/(?P<listslug>[^/]+)/add/$', views.entry_add_view, name='entry-add'),
    url(r'^todolist/list/$', views.todolist_list_view, name='todolist-list'),
    url(r'^todolist/add/$', views.todolist_add_view, name='todolist-add'),
    url(r'^(?P<slug>[^/]+)/$', views.entry_detail_view, name='entry-detail'),
    url(r'^(?P<slug>[^/]+)/edit/$', views.entry_edit_view, name='entry-edit'),
    url(r'^(?P<slug>[^/]+)/delete/$', views.entry_delete_view, name='entry-delete'),
    url(r'^(?P<slug>[^/]+)/assign/$', views.entry_assign_view, name='entry-assign'),
    url(r'^(?P<slug>[^/]+)/assign/me/$', views.entry_assign_me_view, name='entry-assign-me'),
    url(r'^(?P<slug>[^/]+)/unassign/$', views.entry_unassign_view, name='entry-unassign'),
    url(r'^(?P<slug>[^/]+)/complete/$', views.entry_complete_view, name='entry-complete'),
    url(r'^(?P<slug>[^/]+)/complete/me/$', views.entry_complete_me_view, name='entry-complete-me'),
    url(r'^(?P<slug>[^/]+)/incomplete/$', views.entry_incomplete_view, name='entry-incomplete'),
    
    
    url(r'^(?P<todo_slug>[^/]+)/comment/$', views.comment_create, name='comment'),
    url(r'^comment/(?P<pk>\d+)/$', views.comment_detail, name='comment-detail'),
    url(r'^comment/(?P<pk>\d+)/delete/$', views.comment_delete, name='comment-delete'),
    url(r'^comment/(?P<pk>\d+)/update/$', views.comment_update, name='comment-update'),
]

# namespace for these is 'cosinnus-api'
cosinnus_api_patterns = api_patterns(1, 'todo', True,
    #url(r'^todolist/list/$', views.todolist_list_view_api', name='todolist-list'),
    #url(r'^todolist/list/(?P<pk>[0-9a-zA-Z_-]+)/$', views.todolist_detail_view_api', name='todolist-get'),
    #url(r'^todolist/add/$', views.todolist_add_view_api', name='todolist-add'),
    #url(r'^todolist/delete/(?P<pk>[0-9a-zA-Z_-]+)/$', views.todolist_delete_view_api', name='todolist-delete'),
    #url(r'^todolist/update/(?P<pk>[0-9a-zA-Z_-]+)/$', views.todolist_edit_view_api', name='todolist-update'),

    # TODO SASCHA: change 'todos' to 'todo'
    url(r'^todos/list/$', views.entry_list_view_api, name='todo-list-api'),
    url(r'^todos/list/(?P<pk>[0-9a-zA-Z_-]+)/$', views.entry_detail_view_api, name='todo-get'),
    url(r'^todos/add/$', views.entry_add_view_api, name='todo-add'),
    url(r'^todos/delete/(?P<pk>[0-9a-zA-Z_-]+)/$', views.entry_delete_view_api, name='todo-delete'),
    url(r'^todos/update/(?P<pk>[0-9a-zA-Z_-]+)/$', views.entry_edit_view_api, name='todo-update'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/assign/$', views.entry_assign_view_api, name='entry-assign'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/assign/me/$', views.entry_assign_me_view_api, name='entry-assign-me'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/unassign/$', views.entry_unassign_view_api, name='entry-unassign'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/complete/$', views.entry_complete_view_api, name='entry-complete'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/complete/me/$', views.entry_complete_me_view_api, name='entry-complete-me'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/toggle_complete/me/$', views.entry_toggle_complete_me_view_api, name='entry-toggle-complete-me'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/incomplete/$', views.entry_incomplete_view_api, name='entry-incomplete'),

)

cosinnus_root_patterns = []


urlpatterns = cosinnus_group_patterns + cosinnus_root_patterns

cosinnus_todo/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import six

from builtins import object
from django.db import models, transaction
from django.utils.translation import ugettext_lazy as _
from django.core.cache import cache

from cosinnus.models import BaseTaggableObjectModel
from cosinnus.utils.functions import unique_aware_slugify,\
    clean_single_line_text

from cosinnus_todo.conf import settings
from cosinnus_todo.managers import TodoEntryManager
from cosinnus.utils.permissions import filter_tagged_object_queryset_for_user,\
    check_ug_membership, check_user_superuser, check_object_read_access
from cosinnus.utils.urls import group_aware_reverse
from cosinnus_todo import cosinnus_notifications
from cosinnus import cosinnus_notifications as cosinnus_core_notifications
from django.contrib.auth import get_user_model
from django.utils.timezone import now
from cosinnus.models.tagged import LikeableObjectMixin
from uuid import uuid1

_TODOLIST_ITEM_COUNT = 'cosinnus/todo/itemcount/%d'

PRIORITY_LOW = 1
PRIORITY_MEDIUM = 2
PRIORITY_HIGH = 3

PRIORITY_CHOICES = (
    (PRIORITY_LOW, _('Later')),
    (PRIORITY_MEDIUM, _('Normal')),
    (PRIORITY_HIGH, _('Important')),
)


@six.python_2_unicode_compatible
class TodoEntry(LikeableObjectMixin, BaseTaggableObjectModel):

    SORT_FIELDS_ALIASES = [
        ('title', 'title'),
        ('created', 'created'),
        ('completed_by', 'completed_by'),
        ('priority', 'priority'),
        ('assigned_to', 'assigned_to'),
        ('is_completed', 'is_completed'),
    ]

    due_date = models.DateField(_('Due by'), blank=True, null=True,
        default=None)

    completed_date = models.DateField(_('Completed on'), blank=True,
        null=True, default=None)
    completed_by = models.ForeignKey(settings.AUTH_USER_MODEL,
        verbose_name=_('Completed by'), blank=True, null=True, default=None,
        on_delete=models.SET_NULL, related_name='completed_todos')
    is_completed = models.BooleanField(default=0)

    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL,
        verbose_name=_('Assigned to'), blank=True, null=True, default=None,
        on_delete=models.SET_NULL, related_name='assigned_todos')
    __assigned_to = None # for pre-save purposes

    priority = models.PositiveIntegerField(_('Priority'),
        choices=PRIORITY_CHOICES, default=PRIORITY_MEDIUM)

    note = models.TextField(_('Note'), blank=True, null=True)

    todolist = models.ForeignKey('cosinnus_todo.TodoList',
        verbose_name=_('List'), blank=True, null=True, default=None,
        related_name='todos', on_delete=models.CASCADE)

    objects = TodoEntryManager()

    timeline_template = 'cosinnus_todo/v2/dashboard/timeline_item.html'
    
    class Meta(BaseTaggableObjectModel.Meta):
        ordering = ['is_completed', '-completed_date', '-priority', '-due_date']
        verbose_name = _('Todo')
        verbose_name_plural = _('Todos')

    def __init__(self, *args, **kwargs):
        super(TodoEntry, self).__init__(*args, **kwargs)
        self._todolist = getattr(self, 'todolist', None)
        self.__assigned_to = self.assigned_to

    def __str__(self):
        return self.title
    
    def get_icon(self):
        """ Returns the font-awesome icon specific to this object type """
        return 'fa-tasks'

    def save(self, *args, **kwargs):
        self.is_completed = bool(self.completed_date)
        created = bool(self.pk) == False
        super(TodoEntry, self).save(*args, **kwargs)

        if created:
            # todo was created
            cosinnus_notifications.todo_created.send(sender=self, user=self.creator, obj=self, audience=get_user_model().objects.filter(id__in=self.group.members).exclude(id=self.creator.pk))
        if self.__assigned_to != self.assigned_to:
            session_id = uuid1().int
            # assigned to was changed, send to new assignee
            if self.assigned_to and self.assigned_to != self.request.user:
                cosinnus_notifications.assigned_todo_to_user.send(sender=self, user=self.request.user, obj=self, audience=[self.assigned_to], session_id=session_id)
            # send out a notification to all followers for the change
            followers_except_self = [pk for pk in self.get_followed_user_ids() if not pk in [self.request.user.id]]
            followers_except_self = get_user_model().objects.filter(id__in=followers_except_self)
            cosinnus_notifications.following_todo_assignee_changed.send(sender=self, user=self.creator, obj=self, audience=followers_except_self, session_id=session_id, end_session=True)
            
            
        self._clear_cache()
        self._todolist = self.todolist
        self.__assigned_to = self.assigned_to
    
    def on_save_added_tagged_persons(self, set_users):
        """ Called by the taggable form whenever this object is saved and -new- persons
            have been added as tagged! 
            Overriden from BaseTaggableObject. """
        # exclude creator from audience always
        set_users -= set([self.creator])
        cosinnus_core_notifications.user_tagged_in_object.send(sender=self, user=self.creator, 
                obj=self, audience=list(set_users),
                extra={'mail_template':'cosinnus_todo/notifications/user_tagged_in_todo.txt', 'subject_template':'cosinnus_todo/notifications/user_tagged_in_todo_subj.txt'})
            
    
    def get_absolute_url(self):
        kwargs = {'group': self.group, 'slug': self.slug}
        return group_aware_reverse('cosinnus:todo:entry-detail', kwargs=kwargs)
    
    def get_edit_url(self):
        kwargs = {'group': self.group, 'slug': self.slug}
        return group_aware_reverse('cosinnus:todo:entry-edit', kwargs=kwargs)
    
    def get_delete_url(self):
        kwargs = {'group': self.group, 'slug': self.slug}
        return group_aware_reverse('cosinnus:todo:entry-delete', kwargs=kwargs)

    def can_user_assign(self, user):
        """
        Test if a user can assign this object
        """
        if self.creator_id == user.pk:
            return True
        if self.group.is_admin(user):
            return True
        if check_user_superuser(user):
            return True
        return False

    def _clear_cache(self):
        if self.todolist:
            self.todolist._clear_cache()
        if self._todolist:
            self._todolist._clear_cache()

    def delete(self, *args, **kwargs):
        super(TodoEntry, self).delete(*args, **kwargs)
        self._clear_cache()
        
    @classmethod
    def get_current(self, group, user):
        """ Returns a queryset of the current upcoming events """
        qs = TodoEntry.objects.filter(group=group)
        if user:
            qs = filter_tagged_object_queryset_for_user(qs, user)
        return qs.filter(is_completed=False)
    
    def grant_extra_write_permissions(self, user, **kwargs):
        """ An overridable check for whether this object grants certain users write permissions
            even though by general rules that user couldn't write the object.
            
            For todos, users who are assigned this todo can write to it to finish or reassign it.
            
            @param user: The user to check for extra permissions for """
        only_public_fields = False
        fields = kwargs.get('fields', None)
        if fields:
            # if only a change to todo.assigned_to is requested, 
            # we allow that change if the user is a member of the todo's group
            if len(fields) == 1 and 'assigned_to' in fields:
                only_public_fields = check_ug_membership(user, self.group)
            
        return only_public_fields or self.assigned_to == user

    def get_comment_post_url(self):
        return group_aware_reverse('cosinnus:todo:comment', kwargs={'group': self.group, 'todo_slug': self.slug})
    

@six.python_2_unicode_compatible
class TodoList(models.Model):

    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(max_length=55, blank=True)  # human readable part is 50 chars
    group = models.ForeignKey(settings.COSINNUS_GROUP_OBJECT_MODEL,
        verbose_name=_('Group'), related_name='+', on_delete=models.CASCADE)
    
    GENERAL_TODOLIST_TITLE_IDENTIFIER = '__special__general_todolist__'
    
    class Meta(object):
        ordering = ('title',)
        unique_together = (('group', 'slug'),)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        sid = transaction.savepoint()
        try:
            self.todos.all().delete()
            super(TodoList, self).delete(*args, **kwargs)
        except:
            transaction.savepoint_rollback(sid)
        else:
            transaction.savepoint_commit(sid)

    def save(self, *args, **kwargs):
        unique_aware_slugify(self, 'title', 'slug', group=self.group)
        self.title = clean_single_line_text(self.title)
        super(TodoList, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        kwargs = {'group': self.group, 'listslug': self.slug}
        return group_aware_reverse('cosinnus:todo:list-list', kwargs=kwargs)
    
    def get_delete_url(self):
        kwargs = {'group': self.group, 'slug': self.slug}
        return group_aware_reverse('cosinnus:todo:todolist-delete', kwargs=kwargs)
    
    @property
    def filtered_item_count(self):
        if hasattr(self, 'filtered_items'):
            return self.filtered_items.count()
        return self.item_count()
    
    @property
    def item_count(self):
        #count = getattr(self, '_item_count')
        count = cache.get(_TODOLIST_ITEM_COUNT % self.pk)
        if count is None:
            # Hide completed todos
            count = self.todos.exclude(is_completed__exact=True).count()
            cache.set(_TODOLIST_ITEM_COUNT % self.pk, count)
        return count

    def _clear_cache(self):
        cache.delete(_TODOLIST_ITEM_COUNT % self.pk)
        

cosinnus_todo/templates/todo/todoentry_detail.html
{% extends "todo/base.html" %}
{% load i18n %}
{% block page_title %}Todo List{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="active">{{ todoentry.title }}</li>
{% endblock %}

{% block content %}
<table class="table">
<tr>
    <th class="span2">{% trans "Title" %}</th>
    <td>{{ object.title }}</td>
</tr>
<tr>
    <th>{% trans "Created on" %}</th>
    <td>{{ object.created_date|date:"DATETIME_FORMAT" }}</td>
</tr>
<tr>
    <th>{% trans "Created by" %}</th>
    <td>{{ object.created_by }}</td>
</tr>
<tr>
    <th>{% trans "Due by" %}</th>
    <td>{{ object.due_date|date:"DATETIME_FORMAT" }}</td>
</tr>
<tr>
    <th>{% trans "Completed on" %}</th>
    <td>{{ object.completed_date|date:"DATETIME_FORMAT" }}</td>
</tr>
<tr>
    <th>{% trans "Completed by" %}</th>
    <td>{{ object.completed_by }}</td>
</tr>
<tr>
    <th>{% trans "Assigned to" %}</th>
    <td>{{ object.assigned_to }}</td>
</tr>
<tr>
    <th>{% trans "Priority" %}</th>
    <td>{{ object.get_priority_display }}</td>
</tr>
<tr>
    <th>{% trans "Group" %}</th>
    <td>{{ object.group }}</td>
</tr>
<tr>
    <th>{% trans "Note" %}</th>
    <td>{{ object.note|linebreaksbr }}</td>
</tr>
<tr>
    <th>{% trans "Tags" %}</th>
    <td>
        {% for tag in object.tags.all %}
            {{ tag.name }}
        {% empty %}
            &nbsp;
        {% endfor %}
    </td>
</tr>
<tr>
    <th>{% trans "Actions" %}</th>
    <td>
        <div class="btn-group">
            <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">{% trans "Actions" %} <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'sinn_todo-entry-update' group=group.pk todo=object.id %}"><i class="icon-pencil"></i> {% trans "Update" %}</a></li>
                <li><a href="{% url 'sinn_todo-entry-delete' group=group.pk todo=object.id %}"><i class="icon-trash"></i> {% trans "Delete" %}</a></li>
                <li class="divider"></li>

                {% if object.assigned_to == request.user %}
                    <li><a href="{% url 'sinn_todo-entry-unassign' group=group.pk todo=object.id %}"><i class="icon-star-empty"></i> {% trans "Unassign" %}</a></li>
                    <li><a href="{% url 'sinn_todo-entry-assign' group=group.pk todo=object.id %}"><i></i> {% trans "Assign someone else" %}</a></li>
                {% elif object.assigned_to %}
                    <li><a href="{% url 'sinn_todo-entry-assign-me' group=group.pk todo=object.id %}"><i class="icon-star"></i> {% trans "Assign to me" %}</a></li>
                    <li><a href="{% url 'sinn_todo-entry-unassign' group=group.pk todo=object.id %}"><i class="icon-star-empty"></i> {% trans "Unassign" %}</a></li>
                {% else %}
                    <li><a href="{% url 'sinn_todo-entry-assign-me' group=group.pk todo=object.id %}"><i class="icon-star"></i> {% trans "Assign to me" %}</a></li>
                    <li><a href="{% url 'sinn_todo-entry-assign' group=group.pk todo=object.id %}"><i></i> {% trans "Assign someone else" %}</a></li>
                {% endif %}

                {% if object.is_completed %}
                    <li><a href="{% url 'sinn_todo-entry-uncomplete' group=group.pk todo=object.id %}"><i class="icon-remove"></i> {% trans "Mark incomplete" %}</a></li>
                {% else %}
                    <li><a href="{% url 'sinn_todo-entry-complete-me' group=group.pk todo=object.id %}"><i class="icon-ok"></i> {% trans "Finish yourself" %}</a></li>
                    <li><a href="{% url 'sinn_todo-entry-complete' group=group.pk todo=object.id %}"><i></i> {% trans "Mark complete (other)" %}</a></li>
                {% endif %}
            </ul>
        </div>
    </td>
</tr>
</table>
{% endblock %}

cosinnus_todo/templates/todo/todoentry_form.html
{% extends "todo/base.html" %}
{% load i18n bootstrap_toolkit cosinnus %}
{% load static from staticfiles %}
{% block page_title %}Todo{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% if todoentry %}
        <li><a href="{% url 'sinn_todo-entry-detail' group=group.pk todo=todoentry.id %}">{{ todoentry.title }}</a> <span class="divider">/</span></li>
        {% if form_view == 'update' %}
            <li class="active">{% trans "Update" %}</li>
        {% elif form_view == 'assign' or form_view == 'assign-me' %}
            <li class="active">{% trans "Assign" %}</li>
        {% elif form_view == 'complete' or form_view == 'complete-me' %}
            <li class="active">{% trans "Mark complete" %}</li>
        {% elif form_view == 'delete' %}
            <li class="active">{% trans "Delete" %}</li>
        {% elif form_view == 'unassign' %}
            <li class="active">{% trans "Unassign" %}</li>
        {% elif form_view == 'uncomplete' %}
            <li class="active">{% trans "Mark incomplete" %}</li>
        {% endif %}
    {% else %}
        <li class="active">{% trans "Create new" %}</li>
    {% endif %}
{% endblock %}

{% block subnav_add_right %}{% endblock %}

{% block extrahead %}
    {{ block.super }}
    {{ form.media }}
    <link rel="stylesheet" href="{% static 'css/vendor/jquery-ui-autocomplete.min.css' %}">
{% endblock %}

{% block content %}
<form action="." method="post" class="form-horizontal">
    {% csrf_token %}
    <fieldset>
        {{ form|as_bootstrap }}

        {% set submitbtn_caption = "" %}
        {% set question = "" %}
        {% set btnclass = "btn-primary" %}

        {% if form_view == 'create' %}
            {% trans "Create" as submitbtn_caption %}
        {% elif form_view == 'update' %}
            {% trans "Save" context "sinn" as submitbtn_caption %}
        {% elif form_view == 'assign' %}
            {% trans "Assign" as submitbtn_caption %}
        {% elif form_view == 'assign-me' %}
            {% trans "Assign" as submitbtn_caption %}
            {% trans "Do you want to assign the task to yourself?" as question %}
        {% elif form_view == 'complete' %}
            {% trans "Mark complete" as submitbtn_caption %}
        {% elif form_view == 'complete-me' %}
            {% trans "Mark complete" as submitbtn_caption %}
            {% trans "Are you sure to mark the task as completed?" as question %}
        {% elif form_view == 'delete' %}
            {% trans "Delete" as submitbtn_caption %}
            {% trans "Are you sure to remove this task?" as question %}
            {% set btnclass = "btn-danger" %}
        {% elif form_view == 'unassign' %}
            {% trans "Unassign" as submitbtn_caption %}
            {% trans "Do you want to unassign the task from yourself?" as question %}
        {% elif form_view == 'uncomplete' %}
            {% trans "Mark incomplete" as submitbtn_caption %}
            {% trans "Are you sure to mark the task as incompleted?" as question %}
        {% endif %}

        <div class="control-group">
            {% if question %}
                <label class="control-label">{{ question }}</label>
            {% endif %}
            <div class="controls">
                <button type="submit" class="btn {{ btnclass }}">{{ submitbtn_caption }}</button>
                <a href="{% url 'sinn_todo-entry-list' group=group.pk %}" class="btn">{% trans "Cancel" %}</a>
            </div>
        </div>
    </fieldset>
</form>
{% endblock %}

{% block extrafooter %}
{{ block.super }}
<script type="text/javascript" src="{% static "js/vendor/jquery-ui-autocomplete.min.js" %}"></script>
<script type="text/javascript">
{% if not todoentry %}
$("#id_title").focus();
{% endif %}
var availableTags = [
    {% for tag in tags %}
        "{{ tag }}",
    {% endfor %}
];
</script>
<script type="text/javascript" src="{% static "js/vendor/jquery.ui.autocomplete-tags.js" %}"></script>
{% endblock %}

cosinnus_todo/templates/todo/todoentry_list.html
{% extends "todo/base.html" %}
{% load i18n humanize todo_tags %}
{% block page_title %}Todo List{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% if tag %}
        <li><a href="{% url 'sinn_todo-entry-list' group=group.pk %}">{% trans "List" %}</a> <span class="divider">/</span></li>
        <li class="active">{{ tag.name }}</li>
    {% else %}
        <li class="active">{% trans "List" %}</li>
    {% endif %}
{% endblock %}

{% block subnav_add_right %}
<a href="{% url 'sinn_todo-entry-create' group=group.pk %}" class="btn">{% trans "Create new" %}</a>
{{ block.super }}
{% endblock %}

{% block content %}
{% if tags %}
  {% for tag in tags %}
    <a href="{% url 'sinn_todo-entry-list-filtered' group=group.pk tag=tag.slug %}"><span class="label">{{ tag.name }}</span></a>
  {% endfor %}
{% else %}
  {% trans "No tags available." %}
{% endif %}

{% if object_list %}
<table class="table table-striped">
    <thead>
        <td><a href="{{ request.path }}{{ sort_helper.get_sort_query_by_title }}">{% trans "Title" %}</a></td>
        <td><a href="{{ request.path }}{{ sort_helper.get_sort_query_by_completed_by }}">{% trans "Due by" %}</a></td>
        <td><a href="{{ request.path }}{{ sort_helper.get_sort_query_by_assigned_to }}">{% trans "Assigned to" %}</a></td>
        <td><a href="{{ request.path }}{{ sort_helper.get_sort_query_by_is_completed }}">{% trans "Status" %}</a></td>
        <td>{% trans "Tags" %}</td>
        <td>{% trans "Actions" %}</td>
    </thead>
    {% for object in object_list %}
        <tr class="{% if object.due_date|is_past %}info{% else %}{% if object.priority == 1 %}error{% elif object.priority == 2 %}warning{% else %}success{% endif %}{% endif %}">
            <td><a href="{% url 'sinn_todo-entry-detail' group=group.pk todo=object.id %}">{{ object.title }}</a></td>
            <td>{{ object.due_date|naturaltime|default_if_none:"" }}</td>
            <td>{% if object.assigned_to %}{{ object.assigned_to }}{% endif %}</td>
            <td>
                {% if object.is_completed %}
                    <span class="badge badge-success" title="{{ object.completed_date|date:"DATETIME_FORMAT" }} -- {{ object.completed_by }}">{% trans "Completed" %}</span></td>
                {% else %}
                    <span class="badge badge-important">{% trans "Open" %}</span>
                {% endif %}
            </td>
            <td>
                {% for tag in object.tags.all %}
                    <a href="{% url 'sinn_todo-entry-list-filtered' group=group.pk tag=tag.slug %}"><span class="label">{{ tag.name }}</span></a>
                {% empty %}
                -
                {% endfor %}
            </td>
            <td>
                <div class="btn-group">
                    <a class="btn btn-primary btn-mini" href="{% url 'sinn_todo-entry-detail' group=group.pk todo=object.id %}"><i class="icon-eye-open icon-white"></i> {% trans "Show" %}</a>
                    <a class="btn btn-primary btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'sinn_todo-entry-update' group=group.pk todo=object.id %}"><i class="icon-pencil"></i> {% trans "Edit" %}</a></li>
                        <li><a href="{% url 'sinn_todo-entry-delete' group=group.pk todo=object.id %}"><i class="icon-trash"></i> {% trans "Delete" %}</a></li>
                        <li class="divider"></li>

                        {% if object.assigned_to == request.user %}
                            <li><a href="{% url 'sinn_todo-entry-unassign' group=group.pk todo=object.id %}"><i class="icon-star-empty"></i> {% trans "Unassign" %}</a></li>
                            <li><a href="{% url 'sinn_todo-entry-assign' group=group.pk todo=object.id %}"><i></i> {% trans "Assign someone else" %}</a></li>
                        {% elif object.assigned_to %}
                            <li><a href="{% url 'sinn_todo-entry-assign-me' group=group.pk todo=object.id %}"><i class="icon-star"></i> {% trans "Assign to me" %}</a></li>
                            <li><a href="{% url 'sinn_todo-entry-unassign' group=group.pk todo=object.id %}"><i class="icon-star-empty"></i> {% trans "Unassign" %}</a></li>
                        {% else %}
                            <li><a href="{% url 'sinn_todo-entry-assign-me' group=group.pk todo=object.id %}"><i class="icon-star"></i> {% trans "Assign to me" %}</a></li>
                            <li><a href="{% url 'sinn_todo-entry-assign' group=group.pk todo=object.id %}"><i></i> {% trans "Assign someone else" %}</a></li>
                        {% endif %}

                        {% if object.is_completed %}
                            <li><a href="{% url 'sinn_todo-entry-uncomplete' group=group.pk todo=object.id %}"><i class="icon-remove"></i> {% trans "Mark incomplete" %}</a></li>
                        {% else %}
                            <li><a href="{% url 'sinn_todo-entry-complete-me' group=group.pk todo=object.id %}"><i class="icon-ok"></i> {% trans "Finish yourself" %}</a></li>
                            <li><a href="{% url 'sinn_todo-entry-complete' group=group.pk todo=object.id %}"><i></i> {% trans "Mark complete (other)" %}</a></li>
                        {% endif %}
                    </ul>
                </div>
            </td>
        </tr>
    {% endfor %}
</table>
{% else %}
<p>{% trans "There are no todo entries." %}</p>
{% endif %}
{% endblock %}