cosinnus_todo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from cosinnus.utils.url_patterns import api_patterns
from cosinnus_todo import views

app_name = 'todo'

cosinnus_group_patterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^list/$', views.todo_list_create_view, name='list'),
    url(r'^list/move_element/$', views.move_element_view, name='move-element'),
    url(r'^list/(?P<listslug>[^/]+)/$', views.todo_list_create_view, name='list-list'),
    url(r'^list/(?P<listslug>[^/]+)/show/(?P<todoslug>[^/]+)/$', views.todo_list_create_view, name='todo-in-list-list'),
    url(r'^delete/list/(?P<slug>[^/]+)/$', views.todolist_delete_view, name='todolist-delete'),
    
    url(r'^list/(?P<listslug>[^/]+)/add/$', views.entry_add_view, name='entry-add'),
    url(r'^todolist/list/$', views.todolist_list_view, name='todolist-list'),
    url(r'^todolist/add/$', views.todolist_add_view, name='todolist-add'),
    url(r'^(?P<slug>[^/]+)/$', views.entry_detail_view, name='entry-detail'),
    url(r'^(?P<slug>[^/]+)/edit/$', views.entry_edit_view, name='entry-edit'),
    url(r'^(?P<slug>[^/]+)/delete/$', views.entry_delete_view, name='entry-delete'),
    url(r'^(?P<slug>[^/]+)/assign/$', views.entry_assign_view, name='entry-assign'),
    url(r'^(?P<slug>[^/]+)/assign/me/$', views.entry_assign_me_view, name='entry-assign-me'),
    url(r'^(?P<slug>[^/]+)/unassign/$', views.entry_unassign_view, name='entry-unassign'),
    url(r'^(?P<slug>[^/]+)/complete/$', views.entry_complete_view, name='entry-complete'),
    url(r'^(?P<slug>[^/]+)/complete/me/$', views.entry_complete_me_view, name='entry-complete-me'),
    url(r'^(?P<slug>[^/]+)/incomplete/$', views.entry_incomplete_view, name='entry-incomplete'),
    
    
    url(r'^(?P<todo_slug>[^/]+)/comment/$', views.comment_create, name='comment'),
    url(r'^comment/(?P<pk>\d+)/$', views.comment_detail, name='comment-detail'),
    url(r'^comment/(?P<pk>\d+)/delete/$', views.comment_delete, name='comment-delete'),
    url(r'^comment/(?P<pk>\d+)/update/$', views.comment_update, name='comment-update'),
]

# namespace for these is 'cosinnus-api'
cosinnus_api_patterns = api_patterns(1, 'todo', True,
    #url(r'^todolist/list/$', views.todolist_list_view_api', name='todolist-list'),
    #url(r'^todolist/list/(?P<pk>[0-9a-zA-Z_-]+)/$', views.todolist_detail_view_api', name='todolist-get'),
    #url(r'^todolist/add/$', views.todolist_add_view_api', name='todolist-add'),
    #url(r'^todolist/delete/(?P<pk>[0-9a-zA-Z_-]+)/$', views.todolist_delete_view_api', name='todolist-delete'),
    #url(r'^todolist/update/(?P<pk>[0-9a-zA-Z_-]+)/$', views.todolist_edit_view_api', name='todolist-update'),

    # TODO SASCHA: change 'todos' to 'todo'
    url(r'^todos/list/$', views.entry_list_view_api, name='todo-list-api'),
    url(r'^todos/list/(?P<pk>[0-9a-zA-Z_-]+)/$', views.entry_detail_view_api, name='todo-get'),
    url(r'^todos/add/$', views.entry_add_view_api, name='todo-add'),
    url(r'^todos/delete/(?P<pk>[0-9a-zA-Z_-]+)/$', views.entry_delete_view_api, name='todo-delete'),
    url(r'^todos/update/(?P<pk>[0-9a-zA-Z_-]+)/$', views.entry_edit_view_api, name='todo-update'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/assign/$', views.entry_assign_view_api, name='entry-assign'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/assign/me/$', views.entry_assign_me_view_api, name='entry-assign-me'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/unassign/$', views.entry_unassign_view_api, name='entry-unassign'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/complete/$', views.entry_complete_view_api, name='entry-complete'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/complete/me/$', views.entry_complete_me_view_api, name='entry-complete-me'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/toggle_complete/me/$', views.entry_toggle_complete_me_view_api, name='entry-toggle-complete-me'),
    url(r'^todos/(?P<pk>[0-9a-zA-Z_-]+)/incomplete/$', views.entry_incomplete_view_api, name='entry-incomplete'),

)

cosinnus_root_patterns = []


urlpatterns = cosinnus_group_patterns + cosinnus_root_patterns

cosinnus_todo/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from builtins import object
from django import forms
from django.forms import ValidationError
from django.utils.translation import ugettext_lazy as _

from cosinnus.forms.group import GroupKwargModelFormMixin
from cosinnus.forms.tagged import get_form, BaseTaggableObjectForm
from cosinnus.forms.user import UserKwargModelFormMixin
from cosinnus.forms.widgets import DateTimeL10nPicker

from cosinnus_todo.models import TodoEntry, TodoList, Comment
from cosinnus.forms.attached_object import FormAttachableMixin


class TodoEntryForm(GroupKwargModelFormMixin, UserKwargModelFormMixin,
                    FormAttachableMixin, BaseTaggableObjectForm):

    class Meta(object):
        model = TodoEntry
        fields = ('title', 'due_date', 'assigned_to', 'completed_by',
                  'completed_date', 'priority', 'note')
        widgets = {
            'due_date': DateTimeL10nPicker(),
            'completed_date': DateTimeL10nPicker(),
        }

    def __init__(self, *args, **kwargs):
        super(TodoEntryForm, self).__init__(*args, **kwargs)

        field = self.fields.get('todolist', None)
        if field:
            field.queryset = TodoList.objects.filter(group_id=self.group.id).all()
            
        field = self.fields.get('assigned_to', None)
        if field:
            field.queryset = self.group.actual_members
            field.required = False
            instance = getattr(self, 'instance', None)
            if instance and instance.pk:
                can_assign = instance.can_user_assign(self.user)
                if not can_assign:
                    field.widget.attrs['disabled'] = 'disabled'

        field = self.fields.get('completed_by', None)
        if field:
            field.queryset = self.group.actual_members

    def clean_assigned_to(self):
        assigned_to = self.cleaned_data['assigned_to']
        instance = getattr(self, 'instance', None)
        if not instance or not instance.pk:
            return assigned_to

        if instance.can_user_assign(self.user):
            return assigned_to

        if assigned_to != instance.assigned_to:  # trying to cheat!
            raise ValidationError(
                _('You are not allowed to assign this Todo entry.'),
                code='can_not_assign'
            )
        return assigned_to

    def clean(self):
        new_list = self.cleaned_data.get('new_list', None)
        todolist = self.cleaned_data.get('todolist', None)
        if new_list and todolist:
            del self.cleaned_data['todolist']  # A new list name has been defined
        
        return self.cleaned_data


class _TodoEntryAddForm(TodoEntryForm):

    new_list = forms.CharField(label='New list name', required=False)
    due_date = forms.DateField(required=False)

    class Meta(object):
        model = TodoEntry
        fields = ('title', 'note', 'due_date', 'new_list', 'todolist', 'assigned_to', 'priority')
        widgets = {
            'due_date': DateTimeL10nPicker(),
            'completed_date': DateTimeL10nPicker(),
        }
        
    def clean(self):
        super(_TodoEntryAddForm, self).clean()
        # hack to circumvent django still throwing validation errors in my face on a blank select
        # even though the field is required=False
        if self.cleaned_data.get('assigned_to', None) is None:
            self.instance.assigned_to = None
            del self._errors['assigned_to']
        return self.cleaned_data


TodoEntryAddForm = get_form(_TodoEntryAddForm)


class _TodoEntryUpdateForm(_TodoEntryAddForm):
    
    class Meta(_TodoEntryAddForm.Meta):
        fields = ('title', 'note', 'due_date', 'new_list', 'todolist', 'assigned_to',
                  'completed_by', 'completed_date', 'priority')
        widgets = {
            'due_date': DateTimeL10nPicker(),
            'completed_date': DateTimeL10nPicker(),
        }

TodoEntryUpdateForm = get_form(_TodoEntryUpdateForm)


class TodoEntryAssignForm(TodoEntryForm):

    class Meta(object):
        model = TodoEntry
        fields = ('assigned_to',)


class TodoEntryCompleteForm(TodoEntryForm):

    class Meta(object):
        model = TodoEntry
        fields = ('completed_by', 'completed_date',)
        widgets = {
            'completed_date': DateTimeL10nPicker(),
        }


class TodoEntryNoFieldForm(TodoEntryForm):

    class Meta(object):
        model = TodoEntry
        fields = ()


class TodoListForm(GroupKwargModelFormMixin, forms.ModelForm):

    class Meta(object):
        model = TodoList
        fields = ('title', 'slug', )
        

class CommentForm(forms.ModelForm):

    class Meta(object):
        model = Comment
        fields = ('text',)

cosinnus_todo/templates/cosinnus_todo/attached_object_select_pill.html
<span class="app-todos-attachment">
    <i class="fa fa-tasks"></i> 
    {{text}}
</span>

cosinnus_todo/templates/cosinnus_todo/attached_todos.html
{% load cosinnus_tags %}

{% for todo in todos %}
	<div class="app-todos">
        <div class="btn btn-emphasized w100 {% if not no_indent %}indented{% endif %}" href="{{ todo.get_absolute_url }}">
            <ul class="media-list fine-space">
                <li class="media">
                    {% if todo.assigned_to %}
	                    <a class="pull-left" href="{{ todo.get_absolute_url }}">
	                       {% include "cosinnus/user/user_avatar_image.html" with user=todo.assigned_to %}
	                    </a>
                    {% else %}
	                    <a class="pull-left" href="#">
	                        <i class="fa fa-tasks"></i>
	                    </a>
                    {% endif %}
                    <div class="media-body no-vertical-padding ">
                        {% if todo.is_completed %}<del>{% endif %}<strong><a href="{{ todo.get_absolute_url }}" target="_blank">{{ todo.title }}</a></strong>{% if todo.is_completed %}</del>{% endif %}
                        {% with creator=todo.creator assignee=todo.assigned_to %}
                            <div class="group-annotation">
                                {% if assignee %}
	                                <a href="{{ creator|profile_url }}">
	                                    <i class="fa fa-user"></i>
	                                    {{ creator|full_name }}
	                                </a>
                                {% else %}
                                    <a href="{{ assignee|profile_url }}">
                                        <i class="fa fa-user"></i>
                                        {{ assignee|full_name }}
                                    </a>
                                {% endif %}
                                {% if todo.todolist and not todo.todolist.is_general_list %}
                                    <a href="{{ todo.todolist.get_absolute_url }}">
                                        <i class="fa fa-tasks"></i>
                                        {{ todo.todolist.title }}
                                    </a>
                                {% endif %}
                            </div>
                        {% endwith %}
                    </div>
                </li>
            </ul>
        </div><!-- btn -->
	</div>
{% endfor %}

cosinnus_todo/templates/cosinnus_todo/base.html
{% extends "cosinnus/base.html" %}
{% load i18n %}
{% load static %}

{% block page_title %}@ {{ group.name }} | {% trans "Todo" %}{% endblock page_title %}

{% block extrahead %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/vendor/select2.css' %}">
    <link rel="stylesheet" href="{% static 'css/cosinnus_todo/cosinnus_todo.css' %}">
{% endblock extrahead %}

cosinnus_todo/templates/cosinnus_todo/leftnav_todoentry.html
{% load i18n cosinnus_tags %}

{% captureas href %}{% group_url 'cosinnus:todo:list-list' group=group listslug=active_todolist.slug %}{% endcaptureas %}
{% captureas label %}{% trans "Back to" %} „{{ active_todolist.title }}“ {% endcaptureas %}
{% include "cosinnus/leftnav_button.html" with extra_classes="regular-space" icon="fa-reply" label=label href=href  %}

cosinnus_todo/templates/cosinnus_todo/single_todo.html
{% load i18n cosinnus_tags %}

{% with todo=object %}
	<div class="app-todos">
	    <div class="btn btn-emphasized w100" href="{{ todo.get_absolute_url }}">
	        <ul class="media-list {% if no_space %}fine-space{% else %}large-space{% endif %}">
	            <li class="media">
	                <span class="pull-left">
	                    <i class="fa fa-tasks"></i>
	                </span>
	                <div class="media-body {% if not hide_group_name %}no-vertical-padding{% endif %} ">
                        <span class="annotation mobile-hidden">
	                        {% with creator=todo.creator %}
                                {# {% trans "by" %} #} <strong><a href="{{ creator|profile_url }}" >{{ creator|full_name }}</a></strong> 
	                        {% endwith %}
	                        <span class="moment-data-date" data-date="{{ todo.created|date:'c' }}"></span>
                        </span>
	                    {% if todo.is_completed %}<del>{% endif %}<strong>{{ todo.title }}</strong>{% if todo.is_completed %}</del>{% endif %}
	                    {% if not hide_group_name %}
		                    <div class="group-annotation">
	                            {% include 'cosinnus/group/group_label.html' with group=todo.group %}
	                            <a href="{{ todo.todolist.get_absolute_url }}">- {{ todo.todolist.title}}</a>
		                    </div>
	                    {% endif %}
	                </div>
	            </li>
	        </ul>
	    </div><!-- btn -->
	</div>
{% endwith %}

cosinnus_todo/templates/cosinnus_todo/todo_detail.html
{% extends "cosinnus_todo/base.html" %}
{% load i18n static cosinnus_tags widget_tweaks %}


{% block page_title %}{% trans "Todos" %}: {{group.name}} {% endblock %}
{% block breadcrumb %}
    {{ block.super }}
    
    <li><a href="{% group_url 'cosinnus:todo:list' group=group %}">{% trans "Todos" %}</a></li>
    <li><a href="{% group_url 'cosinnus:todo:list-list' group=group listslug=active_todolist.slug %}">{{ active_todolist.title }}</a></li>
    <li class="active">{{ object.title }}</li>
{% endblock %}

{% block leftnav %}
    {% include 'cosinnus_todo/leftnav_todoentry.html' with active_todolist=active_todolist %}
{% endblock leftnav %}

{% block og_image %}{% if object.attached_images %}{{ COSINNUS_CURRENT_PORTAL.get_domain }}{{ object.attached_images.0.static_image_url }}{% else %}{{ block.super }}{% endif %}{% endblock og_image %}
{% block og_title %}{% if object.title %}{{ object.title }}{% else %}{{ object.note|truncatewords:8 }}{% endif %} - {{ group.name }} - {{ block.super }}{% endblock og_title %}
{% block og_description %}{{ object.note|truncatewords:30 }}{% endblock og_description %}

{% block content %}
    
    {% if object.is_completed %}
	    <div class="alert alert-info alert-dismissable">
	        <i class="fa fa-check fa-3x"></i>
	        <p>
	            {% trans "This todo was completed:" %}
		        <span class="moment-data-date" data-date="{{ object.completed_date|date:"Y-m-d" }}" data-date-style="short" data-date-notooltip="true"></span>
		        {% trans "by" %}&nbsp;
	            {% include 'cosinnus/user/user_label.html' with user=object.completed_by %}
	        </p>
	    </div>
	{% endif %}
    
    <!-- a box with semi transparent background -->
    <div class="content-box">
    
	        <div class="app-todos">
                
                {% include 'cosinnus_todo/single_todo_detailed.html' with object=object %}
                	        
	        </div>
    
    
    </div><!-- content-box -->
{% endblock %}



{% block extrafooter %}
{{ block.super }}

<script type="text/javascript">
    
    var select2Format = function(state) {
        var $originalOption = $(state.element);
    
        if (!state.id) {
            return state.text;
        } else {
            var avatarUrl = $originalOption.data('avatar-url');
            return "<img class='avatar-img' src='"+window.location.origin+avatarUrl+"'/>" + state.text;
        }
    };
    
    var select2Options = {
        formatResult: select2Format,
        formatSelection: select2Format,
        escapeMarkup: function(m) { return m; }
    };
    
    $(".select2-avatar-item").select2(select2Options);
    
</script>


{% endblock extrafooter %}

cosinnus_todo/templates/cosinnus_todo/todoentry_form.html
{% extends "cosinnus_todo/base.html" %}
{% load i18n static cosinnus_tags widget_tweaks thumbnail %}

{% block extrahead %}
    {{ block.super }}
    {% include 'cosinnus/common/simplemde_dependencies.html' with element_id=form.forms.obj.note.id_for_label %}
{% endblock %}

{% block page_title %}{% trans "Todos" %}: {{group.name}} {% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    
    <li><a href="{% group_url 'cosinnus:todo:list' group=group %}">{% trans "Todos" %}</a></li>
    <li><a href="{% group_url 'cosinnus:todo:list-list' group=group listslug=active_todolist.slug %}">{{ active_todolist.title }}</a></li>
    {% if form_view == "add" %}
        <li class="active">{% trans "Add Todo" %}</li>
    {% elif form_view == "edit" %}
        <li><a href="{% group_url 'cosinnus:todo:entry-detail' group=group slug=object.slug %}">{{ object.title }}</a></li>
        <li class="active">{% trans "Edit" %}</li>
    {% endif %}
{% endblock %}

{% block leftnav %}
    {% include 'cosinnus_todo/leftnav_todoentry.html' with active_todolist=active_todolist %}
    
    {% include 'cosinnus/common/help_button_leftnav_for_popup.html' with help_text_id="helptext_9_todo" %}
{% endblock leftnav %}


{% block content %}

{% if form.forms.obj.errors or form.forms.media_tag.errors %}
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-exclamation-triangle fa-3x"></i>
        <p>{% trans "There was an error in one of the fields you entered. Please correct it before saving!" %}</p>
    </div>
{% endif %}
    
<form method="POST" action="{% if form_view == 'add' %}{% group_url 'cosinnus:todo:entry-add' listslug=active_todolist.slug group=group.slug %}{% else %}{% group_url 'cosinnus:todo:entry-edit' group=object.group slug=object.slug %}{% endif %}" class="cosinnus-form form-horizontal" id="todo_edit_form">{% csrf_token %}
    {{ form.forms.obj.non_field_errors }}
    {{ form.forms.media_tag.non_field_errors }}
    <input id="id_todolist" name="todolist" type="hidden" value="{{ active_todolist.pk }}"/>
                                
    
    <!-- a box with semi transparent background -->
    <div class="content-box">
    
        {% trans "Title" as title_label %}
        {% trans "Enter a title for the todo." as title_legend %}
        {% captureas title_html %}
                {% if request.GET.title %}
                    {% render_field form.forms.obj.title class+="form-control" placeholder=title_label value=request.GET.title %}
                {% else %}
                    {% render_field form.forms.obj.title class+="form-control" placeholder=title_label %}
                {% endif %}
        {% endcaptureas %}
        {% include 'cosinnus/fields/default_field.html' with field=form.forms.obj.title legend=title_legend label=title_label field_html=title_html first=True %}
        
        {# SimpleMDE Description Field (gets initialized in extrahead) #}                                   
        {% trans "Description" as description_placeholder %}
        {% trans "Enter a description for the todo" as description_label %}
        {% include 'cosinnus/fields/default_field.html' with field=form.forms.obj.note legend=description_legend label=description_label placeholder=description_placeholder large_field=True %}
              
          
        {% trans "Assigned To" as assigned_to_label %}
        {% captureas assigned_to_html %}
            {{ form.forms.obj.assigned_to.errors }}
            <a class="pull-left select2-avatar select2-avatar-wide">
                <select class="select2-avatar-item" name="assigned_to" id="id_assigned_to">
                    <option value="-1" default selected data-avatar-url="{% static 'images/fragezeichen.png' %}" title="ss"> {% trans "Not assigned" %}</option>
                    {% for user in group_users %}
                        <option {% if form.forms.obj.assigned_to.value == user.pk %}selected {% endif %} value="{{ user.pk }}" data-avatar-url="{% if user.cosinnus_profile.avatar %}{% thumbnail user.cosinnus_profile.avatar 40x40 crop=1 upscale=1 %}{% else %}{% static 'images/jane-doe.png' %}{% endif %}">
                            {{ user|full_name|safe_text }}
                        </option>
                    {% endfor %}
                </select>
            </a>
        {% endcaptureas %}
        {% include 'cosinnus/fields/default_field.html' with field_html=assigned_to_html label=assigned_to_label %} 
        
        
        {% trans "Priority" as priority_label %}
        {% captureas priority_html %}
            {{ form.forms.obj.priority.errors }}
	        <select id="{{ form.forms.obj.priority.id_for_label }}" name="{{ form.forms.obj.priority.html_name }}" 
	            value="{{ form.forms.obj.priority.value }}" style='font-family:Verdana, FontAwesome;'>
                
                {% comment %}  
	                from: http://fontawesome.io/cheatsheet/#social-buttons
	                fa-exclamation-circle [&#xf06a;]
	                fa-exclamation [&#xf12a;]
	                fa-minus [&#xf068;]
                {% endcomment %}
	            {% for value, label in form.forms.obj.priority.field.choices %}        
	                <option value="{{ value }}" {% if  form.forms.obj.priority.value == value %}selected="selected"{% endif %}>
	                    {% if value == 1 %}
	                        &#xf068;
	                    {% elif value == 2 %}
	                        &#xf12a;
	                    {% elif value == 3 %}
	                        &#xf06a;
	                    {% endif %}    
	                    &nbsp; {{ label }}
	                </option>
	            {% endfor %}
	        </select>
        {% endcaptureas %}
        {% include 'cosinnus/fields/default_field.html' with field_html=priority_html label=priority_label %} 
        
        
        {# Regular field with custom HTML #}
		{% trans "Due date" as due_label %}
		{% captureas due_html %}
            {{ form.forms.obj.due_date.errors }}
            {% with formatted_date=form.forms.obj.due_date.value|date:"Y-m-d" %}
                <a id="todoDate"class="moment-data-date" style="display: inline-block; padding: 10px; cursor: pointer;" data-toggle="modal" data-target="#datePickerModal"
		                    onchange="$('#id_due_date').val($('#todo_due_date_select .moment-data-date').attr('data-date'));" data-date-style="short" 
		                    data-date="{% if form.forms.obj.due_date.value %}{% if formatted_date %}{{ formatted_date }}{% else %}{{ form.forms.obj.due_date.value }}{% endif %}{% endif %}" >
                    {% if not form.forms.obj.due_date.value %}{% trans "No date chosen" %}{% endif %}
                </a>
            {% endwith %}
		    <input id="id_due_date" name="due_date" type="hidden" value="{% if form.forms.obj.due_date.value %}{{ form.forms.obj.due_date.value|date:"Y-m-d" }}{% endif %}"/>
            
            <button class="btn btn-emphasized btn-autosize" id="todo_due_date_select" data-dateelement="#todoDate" data-toggle="modal" data-target="#datePickerModal">
		        <ul class="media-list">
		            <li class="media">
		                <span class="pull-left">
		                    <i class="fa fa-clock-o"></i>
		                </span>
		                <div class="media-body">
		                    {% trans "Choose due date" %}...
		                </div>
		            </li>
		        </ul>
		    </button>
		{% endcaptureas %}
		{% include 'cosinnus/fields/default_field.html' with field=fffffffffffffffffffffff field_html=due_html label=due_label %}
		        
	                            
        {% include 'cosinnus/media_tags.html' with show_persons=True %}
	                            
    </div><!-- content-box -->
    
    
    <button type="submit" class="btn btn-emphasized" id="createDoodleButton">
        <ul class="media-list">
            <li class="media">
                <span class="pull-left">
                    <i class="fa fa-pencil"></i>
                </span>
                <div class="media-body">
                    {% if form_view == "add" %}
                      {% trans "Create" %}
                    {% elif form_view == "edit" %}
                      {% trans "Save" %}
                    {% endif %}
                </div>
            </li>
        </ul>
    </button>
    
</form>
        
        
        
<!-- Pick Date Modal -->
<div class="modal fade" id="datePickerModal" tabindex="1" role="dialog" aria-labelledby="datePickerLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="fa fa-times"></i>
                </button>
                <h4 class="modal-title" id="datePickerLabel">
                    <i class="fa fa-calendar"></i>
                    {% trans "Choose day" %}
                </h4>
            </div>
            <div class="modal-body">
                <p>{% trans "Until when should the task be completed?" %}</p>
                <div class="small-calendar" data-dateelement=""></div>
            </div>
            <div class="modal-footer">
                <button type="button" id="datePickerModal_submit" class="btn btn-emphasized"  data-dismiss="modal">
                    <ul class="media-list">
                        <li class="media">
                            <span class="pull-left">
                                <i class="fa fa-check"></i>
                            </span>
                            <div class="media-body">
                                {% trans "OK" %}
                            </div>
                        </li>
                    </ul>
                </button>
            </div>
        </div>
    </div>
</div><!-- modal -->
        
    
    
{% endblock %}



{% block extrafooter %}
{{ block.super }}

<script type="text/javascript">
    
    var select2Format = function(state) {
        var $originalOption = $(state.element);
    
        if (!state.id) {
            return state.text;
        } else {
            var avatarUrl = $originalOption.data('avatar-url');
            return "<img class='avatar-img' src='"+window.location.origin+avatarUrl+"'/>" + state.text;
        }
    };
    
    var select2Options = {
        formatResult: select2Format,
        formatSelection: select2Format,
        escapeMarkup: function(m) { return m; }
    };
    
    $(".select2-avatar-item").select2(select2Options);
    
</script>


{% endblock extrafooter %}

cosinnus_todo/templates/cosinnus_todo/todolist_form.html
{% extends "cosinnus_todo/base.html" %}
{% load i18n cosinnus_tags bootstrap3 %}


{% block page_title %}
    {% trans "Todo lists" %} {{ block.super }}
{% endblock page_title %}


{% block content_title %}
{{ group.name }}: {% trans "Todo lists" %}
{% endblock content_title %}


{% block subnav_add_right %}{% endblock %}

{% block content %}
    <form action="." method="post" class="form-horizontal">
        {% csrf_token %}
        
        {% bootstrap_form form layout='horizontal' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
                <a href="{% group_url 'cosinnus:todo:list' group=group %}" class="btn">{% trans "Cancel" %}</a>
            </div>
        </div>
    </form>
{% endblock %}